### PR TITLE
Fix/consistent test and version

### LINKED ISSUE #50: Make test folders consistent with common usage
- Move conftest.py to the test folders
- rename test-requirements.txt to requirements_test.txt
- add single-source version numbers to each template

### PR DESCRIPTION
**Pull request by jgd10**
1. Moved conftest.py into the tests folder in each template (it should
   normally be in there and I do not know why it was not before).

2. Added an `__init__.py` and a `_version.py` to each project so that
   there is a single location to store the version for all projects

3. Renamed test-requirements.txt to the more consistent
   requirements_test.txt, which is more common in Python

closes #50

### CODE REVIEW

**Review by asbfall — COMMENTED** [review]
1. Moved conftest.py into the tests folder in each template (it should
   normally be in there and I do not know why it was not before).  -> **OK**

The reason 

2. Added an `__init__.py` and a `_version.py` to each project so that
   there is a single location to store the version for all projects

3. Renamed test-requirements.txt to the more consistent
   requirements_test.txt, which is more common in Python -> **Ok but I do not agree with the statement 'more common used in Python'**

**Review by asbfall — COMMENTED** [review]
Unless I miss it I do not see the changes for the rest-api tests dockerfile

**Comment by jgd10** [comment]
I should add that it is more common in my experience and is the practice in the rest of PyAnsys

**Comment by jgd10** [comment]
> Unless I miss it I do not see the changes for the rest-api tests dockerfile

This PR was made before those changes were added, so they are not included.

**Pull request merged**
